# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz


    joint_state_broadcaster:	#自定义一个广播节点状态的广播者名字
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_forward_controller:
      type: forward_command_controller/ForwardCommandController


robotic_arm_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:		#关节接受位置/速度/力矩输入
      - position
      - velocity
      - effort
    state_interfaces:		#关节反馈位置和速度
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true